camel:
  springboot:
    name: account-service
    main-run-controller: true
  zipkin:
    host-name: 127.0.0.1
    port: 9410
    server-service-mappings.direct*: consul-acc-reg
    client-service-mappings.direct*: consul-acc-reg
    server-service-mappings.route*: account-service
    client-service-mappings.route*: account-service

spring:
  main:
    sources: com.gykan.services.account.AccountRouter

logging:
  level:
    org.apache.camel: DEBUG
